DECLARE

CURSOR C1 IS

select ITM_CD ITM_CD ,LANDED_COST,BR_CD,PG_CD from LIG_ITM_LIST A ;

I NUMBER:=0;
CNT NUMBER ;
BEGIN

FOR MREC IN C1
LOOP

I:=I+1;
BEGIN

SELECT COUNT(*) INTO CNT FROM light_item_master WHERE ITM_CD=MREC.ITM_CD and BR_CD =MREC.BR_CD; 

IF CNT= 0 THEN 

INSERT INTO light_item_master values(MREC.PG_CD,MREC.BR_CD,NULL,NULL,MREC.ITM_CD,MREC.LANDED_COST);

ELSE 
UPDATE light_item_master
SET LANDED_COST=MREC.LANDED_COST
WHERE br_cd=MREC.BR_CD and ITM_CD=MREC.ITM_CD;
END IF;
END;

END LOOP;
COMMIT;


DBMS_OUTPUT.PUT_LINE('I='||I);
END;
/
