set lines 200
col USER_CONCURRENT_QUEUE_NAME for a150;
select T.USER_CONCURRENT_QUEUE_NAME,B.RUNNING_PROCESSES,B.MAX_PROCESSES
from apps.FND_CONCURRENT_QUEUES_TL T, apps.FND_CONCURRENT_QUEUES B
where B.APPLICATION_ID = T.APPLICATION_ID
and B.CONCURRENT_QUEUE_ID = T.CONCURRENT_QUEUE_ID
and T.LANGUAGE = userenv('LANG');
