SELECT "A1"."PERIOD_NAME","A1"."PERIOD_TYPE","A1"."PERIOD_YEAR",
"A1"."END_DATE","A1"."END_DATE","A1"."START_DATE","A2"."PERIOD_N
ET_DR","A2"."PERIOD_NET_CR","A2"."CODE_COMBINATION_ID","A2"."PER
IOD_NAME","A2"."PERIOD_TYPE","A2"."PERIOD_YEAR","A2"."ACTUAL_FLA
G","A2"."CURRENCY_CODE","A3"."SEGMENT2","A3"."SEGMENT4","A3"."SE
GMENT3","A3"."SEGMENT4","A3"."SEGMENT4","A3"."SEGMENT3","A3"."SE
GMENT6","A3"."SEGMENT6","A3"."CODE_COMBINATION_ID","A3"."SEGMENT
8","A3"."SEGMENT4","A3"."SEGMENT2","A3"."SEGMENT3","A3"."SEGMENT
4","A3"."SEGMENT6" FROM "APPS"."GL_PERIODS" "A1","APPS"."GL_BALA
NCES" "A2","APPS"."GL_CODE_COMBINATIONS" "A3" WHERE "A3"."SEGMEN
T8"='0000000000' AND "A3"."SEGMENT4"<>'026' AND "A2"."CODE_COMBI
NATION_ID"="A3"."CODE_COMBINATION_ID" AND "A2"."CURRENCY_CODE"='
INR' AND "A2"."ACTUAL_FLAG"='A' AND "A1"."PERIOD_NAME"="A2"."PER
IOD_NAME" AND "A1"."PERIOD_TYPE"="A2"."PERIOD_TYPE" AND "A1"."PE
RIOD_YEAR"="A2"."PERIOD_YEAR" AND "A1"."END_DATE">=:1 AND "A1"."
END_DATE"<=:2 AND "A1"."START_DATE"<>DECODE(SUBSTR(:3,1,6),'31-M
AR','28-MAR-2010',:4)
