CREATE TABLE HRIS.EMP_CTC_AFTER_PMS
(
  FIN_YEAR                     NUMBER,
  EMP_CD                       VARCHAR2(4 BYTE),
  GRADE_NEW                    VARCHAR2(4 BYTE),
  COST_CENTER                  VARCHAR2(8 BYTE),
  COST_CENTER_DESC             VARCHAR2(8 BYTE),
  BRCODE                       VARCHAR2(4 BYTE),
  POSID                        VARCHAR2(4 BYTE),
  CONVEYANCE_SCHEME            VARCHAR2(10 BYTE),
  SITE_FLAG                    VARCHAR2(4 BYTE),
  SA_FLAG                      VARCHAR2(4 BYTE),
  NPS_FLAG                     VARCHAR2(4 BYTE),
  BASIC                        NUMBER(25),
  HRA                          NUMBER(25),
  ADDN_ALLOW                   NUMBER(25),
  CONV_AMT                     NUMBER(25),
  MEDICAL_ALLOW                NUMBER(25),
  CAR_ALLOW                    NUMBER(25),
  SPL_ALLOW                    NUMBER(25),
  FUEL_MAINT_ALLOW             NUMBER(25),
  DRIVER_ALLOW                 NUMBER(25),
  PHONE                        NUMBER(25),
  HEALTH_CHECKUP               NUMBER(25),
  FUEL_MAINT_ALLOW_DIFF        NUMBER(25),
  DRIVER_ALLOW_DIFF            NUMBER(25),
  PHONE_DIFF                   NUMBER(25),
  HEALTH_CHECKUP_DIFF          NUMBER(25),
  NPS                          NUMBER(25),
  SITE_ALLOW                   NUMBER(25),
  SITE_ACCOMMODATION_ALLOW     NUMBER(25),
  PF                           NUMBER(25),
  GRATUITY                     NUMBER(25),
  SA                           NUMBER(25),
  LTA                          NUMBER(25),
  BONUS                        NUMBER(25),
  INS_PREMIUM                  NUMBER(25),
  ANNUAL_CTC_BEFORE_INCENTIVE  NUMBER(25),
  GRADE_EXCELLENT_INC          NUMBER(25),
  TOTAL_CTC                    NUMBER(30),
  FUEL_MAINT_ALLOW_POLICY      NUMBER(30),
  CONV_AMT_POLICY              NUMBER(30),
  FINAL_PMS_CTC                NUMBER(30),
  PROMOTABILITY                VARCHAR2(5 BYTE),
  LAST_UPD_BY                  VARCHAR2(4 BYTE),
  LAST_UPD_DT                  DATE,
  IP                           VARCHAR2(50 BYTE)
);
